//LOGIN
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGOUT_USER = "LOGOUT_USER";

//DS
export const GET_DS_SUCCESS = "GET_DS_SUCCESS";
export const GET_DS_FAILURE = "GET_DS_FAILURE";
export const GET_DS_REQUEST = "GET_DS_REQUEST";

//ANSWERS BY CASE ID
export const GET_ANSWERS_BY_CASEID_SUCCESS = "GET_ANSWERS_BY_CASEID_SUCCESS";
export const GET_ANSWERS_BY_CASEID_FAILURE = "GET_ANSWERS_BY_CASEID_FAILURE";
export const GET_ANSWERS_BY_CASEID_REQUEST = "GET_ANSWERS_BY_CASEID_REQUEST";

//ANSWERS
export const GET_ANSWERS_SUCCESS = "GET_ANSWERS_SUCCESS";
export const GET_ANSWERS_FAILURE = "GET_ANSWERS_FAILURE";
export const GET_ANSWERS_REQUEST = "GET_ANSWERS_REQUEST";
export const COPY_TEXT_TO_SEARCH = "COPY_TEXT_TO_SEARCH";
export const CLEAR_CASE_DETAILS = "CLEAR_CASE_DETAILS";

//QUERY DATA
export const GET_QUERY_DATA_BY_CASE_ID_SUCCESS =
  "GET_QUERY_DATA_BY_CASE_ID_SUCCESS";
export const GET_QUERY_DATA_BY_CASE_ID_FAILURE =
  "GET_QUERY_DATA_BY_CASE_ID_FAILURE";
export const GET_QUERY_DATA_BY_CASE_ID_REQUEST =
  "GET_QUERY_DATA_BY_CASE_ID_REQUEST";

//COMMENTS
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAILURE = "GET_COMMENTS_FAILURE";
export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";

//SIMILAR TICKETS
export const GET_SIMILAR_TICKETS_SUCCESS = "GET_SIMILAR_TICKETS_SUCCESS";
export const GET_SIMILAR_TICKETS_FAILURE = "GET_SIMILAR_TICKETS_FAILURE";
export const GET_SIMILAR_TICKETS_REQUEST = "GET_SIMILAR_TICKETS_REQUEST";

//SELECTED CASES
export const ADD_SELECTED_CASE = "ADD_SELECTED_CASE";
export const REMOVE_SELECTED_CASE = "REMOVE_SELECTED_CASE";

//EDITOR
export const COPY_TEXT_TO_EDITOR = "COPY_TEXT_TO_EDITOR";
export const CLEAR_EDITOR = "CLEAR_EDITOR";
export const SAVE_LAYOUT_CONFIG = "SAVE_LAYOUT_CONFIG";

//SNACKBAR
export const SET_NEW_SNACKBAR_MESSAGE = "SET_NEW_SNACKBAR_MESSAGE";
export const CLEAN_SNACKBAR_MESSAGE = "CLEAN_SNACKBAR_MESSAGE";

//CUSTOM MENU
export const SAVE_CUSTOM_MENU_SUCCESS = "SAVE_CUSTOM_MENU_SUCCESS";
export const SAVE_CUSTOM_MENU_FAILURE = "SAVE_CUSTOM_MENU_FAILURE";
export const SAVE_CUSTOM_MENU_REQUEST = "SAVE_CUSTOM_MENU_REQUEST";

//SIMULATIONS
export const GET_SIMULATION_FRAMES_SUCCESS = "GET_SIMULATION_FRAMES_SUCCESS";
export const GET_SIMULATION_FRAMES_FAILURE = "GET_SIMULATION_FRAMES_FAILURE";
export const GET_SIMULATION_FRAMES_REQUEST = "GET_SIMULATION_FRAMES_REQUEST";
